"""Slide engine using python-pptx to generate PowerPoint presentations.

Generates native .pptx files from structured data or by assembling
images (like those generated by the figure/diagram engines).
"""
import os
from typing import List, Dict, Any, Optional
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt

def create_presentation(
    slides_data: List[Dict[str, Any]],
    output_path: str,
    template_path: Optional[str] = None
) -> str:
    """Generate a `.pptx` presentation.
    
    Args:
        slides_data: List of dictionaries describing each slide.
                     Required keys depend on the slide layout.
                     Example: {"title": "Slide 1", "content": "Bullet 1\nBullet 2"}
                     or {"title": "Chart", "image": "path/to/fig.svg"}
        output_path: Where to save the presentation.
        template_path: Optional .pptx file to use as a base styling template.
        
    Returns:
        Absolute path to the generated presentation.
    """
    if template_path and os.path.exists(template_path):
        prs = Presentation(template_path)
    else:
        prs = Presentation()
        
    # Standard layouts (0: Title, 1: Title and Content, 5: Title Only, 6: Blank)
    layout_title_content = prs.slide_layouts[1]
    layout_title_only = prs.slide_layouts[5]
    
    for slide_data in slides_data:
        title = slide_data.get("title", "")
        content = slide_data.get("content", "")
        image_path = slide_data.get("image")
        
        if image_path:
            # Layout with mostly image
            slide = prs.slides.add_slide(layout_title_only)
            if slide.shapes.title:
                slide.shapes.title.text = title
            
            # Place image centered
            # In python-pptx, dimensions are required. Let's use Inches
            # Standard widescreen is 13.33 x 7.5 inches.
            # We'll put the image roughly in the middle, scaling height to fit
            try:
                # Top down a bit to leave room for title
                top = Inches(1.5)
                left = Inches(1.5)
                height = Inches(5.0) 
                # Provide height and letting it auto-scale width
                slide.shapes.add_picture(image_path, left, top, height=height)
            except Exception as e:
                print(f"Warning: Could not add image {image_path}: {e}")
                
        else:
            # Bullet point slide
            slide = prs.slides.add_slide(layout_title_content)
            if slide.shapes.title:
                slide.shapes.title.text = title
                
            if slide.shapes.placeholders and len(slide.shapes.placeholders) > 1:
                body_shape = slide.shapes.placeholders[1]
                tf = body_shape.text_frame
                tf.text = content
                
    # Save
    out_file = Path(output_path).resolve()
    out_file.parent.mkdir(parents=True, exist_ok=True)
    
    prs.save(str(out_file))
    return str(out_file)
