"""Slide engine using python-pptx to generate PowerPoint presentations.

Generates native .pptx files from structured data or by assembling
images (like those generated by the figure/diagram engines).
"""
import logging
import os
from typing import List, Dict, Any, Optional
from pathlib import Path
import tempfile
import subprocess

from pptx import Presentation
from pptx.util import Inches

logger = logging.getLogger(__name__)


def _convert_svg_to_png(svg_path: str) -> Optional[str]:
    """Convert an SVG file to a temporary PNG.

    Tries multiple backends: cairosvg (python), rsvg-convert (cli), inkscape (cli).
    Returns the temp PNG path on success, or None on failure.
    """
    temp_png = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
    temp_png.close()
    png_path = temp_png.name

    # Strategy 1: cairosvg (pure Python, best option)
    try:
        import cairosvg
        cairosvg.svg2png(url=svg_path, write_to=png_path, output_width=1920)
        return png_path
    except ImportError:
        pass
    except Exception as exc:
        logger.debug("cairosvg failed for %s: %s", svg_path, exc)

    # Strategy 2: rsvg-convert (common on macOS via brew install librsvg)
    try:
        subprocess.run(
            ["rsvg-convert", "-f", "png", "-w", "1920", "-o", png_path, svg_path],
            check=True,
            capture_output=True,
        )
        return png_path
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass

    # Strategy 3: inkscape CLI
    try:
        subprocess.run(
            ["inkscape", svg_path, "--export-type=png", f"--export-filename={png_path}",
             "--export-width=1920"],
            check=True,
            capture_output=True,
        )
        return png_path
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass

    # All strategies failed — clean up and return None
    if os.path.exists(png_path):
        os.unlink(png_path)
    logger.warning(
        "Could not convert SVG '%s' to PNG. Install cairosvg, librsvg, or inkscape.",
        svg_path,
    )
    return None


def _add_bullets(text_frame, content: str) -> None:
    """Parse content string into properly separated bullet paragraphs.

    Each line becomes a separate paragraph.  Lines starting with '- ' or
    '• ' have the prefix stripped.  The first paragraph reuses the existing
    (empty) paragraph; subsequent ones are appended.
    """
    lines = content.split("\n")
    for idx, line in enumerate(lines):
        clean = line.strip()
        if not clean:
            continue
        # Strip leading bullet markers
        for prefix in ("- ", "• ", "* "):
            if clean.startswith(prefix):
                clean = clean[len(prefix):]
                break

        if idx == 0:
            text_frame.text = clean
        else:
            p = text_frame.add_paragraph()
            p.text = clean
            p.level = 0


def create_presentation(
    slides_data: List[Dict[str, Any]],
    output_path: str,
    template_path: Optional[str] = None,
) -> str:
    """Generate a `.pptx` presentation.

    Args:
        slides_data: List of dicts describing each slide.
            Keys: ``title``, ``content`` (bullet text, newline-separated),
            ``image`` (path to image file), ``notes`` (speaker notes).
        output_path: Where to save the presentation.
        template_path: Optional .pptx file to use as a base styling template.

    Returns:
        Absolute path to the generated presentation.
    """
    if template_path and os.path.exists(template_path):
        prs = Presentation(template_path)
    else:
        prs = Presentation()

    # Standard layouts: 0=Title, 1=Title+Content, 5=Title Only, 6=Blank
    layout_title_content = prs.slide_layouts[1]
    layout_title_only = prs.slide_layouts[5]

    for slide_data in slides_data:
        title = slide_data.get("title", "")
        content = slide_data.get("content", "")
        image_path = slide_data.get("image")
        notes_text = slide_data.get("notes", "")

        if image_path and os.path.exists(image_path):
            slide = prs.slides.add_slide(layout_title_only)
            if slide.shapes.title:
                slide.shapes.title.text = title

            actual_image_path: Optional[str] = image_path
            temp_png_path: Optional[str] = None

            if str(image_path).lower().endswith(".svg"):
                temp_png_path = _convert_svg_to_png(image_path)
                actual_image_path = temp_png_path

            if actual_image_path and os.path.exists(actual_image_path):
                try:
                    top = Inches(1.5)
                    left = Inches(1.5)
                    height = Inches(5.0)
                    slide.shapes.add_picture(actual_image_path, left, top, height=height)
                except Exception as exc:
                    logger.error("Could not add image '%s': %s", actual_image_path, exc)

            # Clean up temp file
            if temp_png_path and os.path.exists(temp_png_path):
                os.unlink(temp_png_path)

        elif image_path and not os.path.exists(image_path):
            logger.warning("Image file not found: %s. Creating title-only slide.", image_path)
            slide = prs.slides.add_slide(layout_title_only)
            if slide.shapes.title:
                slide.shapes.title.text = title

        else:
            # Bullet point slide
            slide = prs.slides.add_slide(layout_title_content)
            if slide.shapes.title:
                slide.shapes.title.text = title

            if content and slide.shapes.placeholders and len(slide.shapes.placeholders) > 1:
                body_shape = slide.shapes.placeholders[1]
                _add_bullets(body_shape.text_frame, content)

        # Speaker notes
        if notes_text:
            notes_slide = slide.notes_slide
            notes_slide.notes_text_frame.text = notes_text

    # Save
    out_file = Path(output_path).resolve()
    out_file.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(out_file))
    return str(out_file)
